// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4a819d42-99ed-4c9c-94ee-b5583b7eec5a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HwVn5SjcG",
    "aws_user_pools_web_client_id": "3h9k3nk8ia3576fqa8r798ib5g",
    "oauth": {}
};


export default awsmobile;
